from pipeline.instances import instances
import numpy as np
import math
import copy

#########################################################################
#################   SOLVER ATO PRICING - MULTI-STAGE    #################
#########################################################################

### PARAMETERS ###

##############################################
# GENERAL SIZE #
comp = 5
prod = 4
stages = 8                     
branching = [2,2,2,2,2,2,2]   # Binary tree
scenarios = math.prod(branching)   # 128 scenarios
##############################################

##############################################
# Out of Sample (OOS) tree
# Topología Out-of-Sample (Evaluación)
oos_branching = [10, 5, 4, 2, 2, 1, 1] # 800 escenarios
oos_scenarios = math.prod(oos_branching)
##############################################


##############################################
# BILL OF MATERIALS 
# Here we have 2 options: 
#   define randomly the BoM, where products use an amount of components between [min_use, max_use]
#   or use a specific BoM defined in parameters.py (W model, N model, etc)
min_use = 3
max_use = 4
other = False
##############################################


##############################################
# PRICES
# The discrete set of prices defined by [lb_price, ub_price] in steps of step_price.
# i.e, the discrete set [30,50] in steps of 2: [30, 32, 34,..., 48, 50]
lb_price = 15
ub_price = 60
step_price = 5
##############################################


##############################################
# COSTS
# Similar to how the discrete set of prices work. Define the set [min_cost, max_cost] in steps of five 
# (the steps can be modified in params.py)
min_cost = 5
max_cost = 25
inv_factor = 0.2
# I0: quantity to satisfy expected demand at given price
# select price --> determine expected demand --> satisfy initial inventory 
I0 = np.max([lb_price, ub_price]) # Currently set to satisfy minimum expected demand (>0)
##############################################

##############################################
# MULTIPLICATIVE STOCHASTIC COMPONENT - DEMAND
# epsilon: given by a uniform distribution U[lb_epsilon, ub_epsilon]
lb_epsilon = 0.7
ub_epsilon = 1.3
##############################################
# ADDITIVE STOCHASTIC COMPONENT - DEMAND
# delta: given by a normal distribution N(mu_delta, std_delta)
mu_delta = 0
std_delta = 2
#############################################
# PRICE LINEAR EXPRESSION - DEMAND
# Decreasing linnear expression for the demand. given by: (a - b * w)
a = 100
b = 1.6
# Full demand expression given by: epsilon[t,s] * (a - b * w[j,t,p,s]) + delta[j,t,s]
##############################################

##############################################
# LEAD TIMES
# lead times are randomly generated by a uniform dist U[lb_L,ub_L]. 
# in our work we can simply change between deterministic or stochastic lead times. 
#   For deterministic: L = L[i,t]
#   For stochastic: L = L[i,t,s]
lb_L = 1
ub_L = 2
det = False # False for stochastic lead times (While we tested with deterministic, we mostly focus in stochastic)
##############################################

##############################################
# UNCERTAINTY ANALYSIS 
# We can calculate the following metrics for uncertainty analysis:
#   - VSS: Value of the Stochastic Solution
#   - EVPI: Expected Value of Perfect Information
#   - VSS_TS: Value of Stochastic Solution based on two stage model

vss_calc = False
evpi_calc = False
vss_ts_calc = False   
##############################################


##############################################
# EXPERIMENTAL SETTINGS (True / False)
show_var = False   # export solution in an excel file. Can be used for fine analisys of decision behavior.
#=============================================
lambda_app = False   # Use lambda approximation to extract affine policy and evaluate in MS_linear with w fixed [OLD, NOW AF_EVAL MODEL]
show_heatmap = False   # Save heatmaps to figures for every decision variable
show_boxplot = False   # Save boxplot to figures for every decision variable
show_candlestick = False   # Save candlestick to figures for every decision variable
#=============================================
show_kpis = True   # Calculate and print KPIs for fulfillment, utilization, inventory ratio and weighted average price
#=============================================
time_limit = 900 # limit for each iteration
seed = 5
iter = 15 # 1 for a single instance. >2 for several (mean results, odd number recommended)
#=============================================
#=============================================


#=============================================
#=============================================366
# SPECIFIC INSTANCE CONFIGS
#=============================================
# Here we can use very specific instances from the literature. All will be detailed in params.py and generator.py
# These instances include all but stages, scenario tree and lead time distribution.
#=============================================
inst = "None"
#=============================================
# "None" -> Manual input of parameters. Beware of infeasibility!
# "Oh_et_al_1" -> Simple W model (3x2) based on Oh et al. (2014)
# "Oh_et_al_2" -> 5x4 model used by Akçay & Xu (2004) and Oh et al. (2014)
# "Oh_et_al_3" -> 11 x 11 instance based on Oh et al. (2014)
#=============================================

from data.config import (ProblemSize, BomConfig, CostConfig, PriceConfig,
                     DemandConfig, LeadTimeConfig, RunConfig, OutputConfig, ExperimentConfig)

size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit, 
                   None, oos_branching, oos_scenarios)
bom = BomConfig(min_use, max_use, other)
costs = CostConfig(min_cost, max_cost, inv_factor, I0)
price = PriceConfig(lb_price, ub_price, step_price)
demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
lead_times = LeadTimeConfig(lb_L, ub_L, det)
Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                    vss_calc, evpi_calc, vss_ts_calc)

#=============================================
# SPECIFIC CONFIGS
#=============================================
# in this research we explore the ATO problem with several model formulations. They are detailed below.
# depending on their nature, they will be in either the models or the sol_approach folders.
#============================================
#   "MS" -> Standard multistage model (non-linear).
#============================================
#   "MS_linear" -> multistage with linealized revenue (MILP). 
#============================================
#   "MS_linear_affine" -> multistage with linealized revenue AND affine pricing policy.
#============================================
#   "AF_EVAL" -> Solves MS_linear_affine, extract and approximate affine policy to binary, evaluate in MS_linear with w fixed.
#   "REL_EVAL" -> Solve relaxed MS_linear, extract and approximate affine policy to binary, evaluate in MS_linear with w fixed.
#============================================
#   "IH" -> iterative heuristic: iterates between solving pricing problem and inventory problem (features vector contains inventory levels from inventory problem)
#============================================
# Others:
#   "TS_linear" -> Two stage version of MS_linear model.
#   "TS_linear_affine" -> two-stage with linearized revenue AND affine pricing policy (x here-and-now).
#   "Relaxed_eval" ->  Relax MS_linear , extract and approximate cts policy to binary, evaluate in MS_linear with w fixed.
#============================================

# ==============================================================================
# Ejecuciones (switch True / False)
#============================================
single = False # True for single instance
comp_sweep = False
prod_sweep = False
branching_sweep = False
lead_time_sweep = False
dem_sweep = False
oos_sweep = True
#============================================


# ==============================================================================
# EJECUCIÓN INDIVIDUAL DE MODELOS
# ==============================================================================
if single:
    run_configs = [
        # RunConfig(Model="MS_linear", W_cts=True),
        # # RunConfig(Model="MS_linear_affine", W_cts=False),
        # RunConfig(Model="AF_EVAL"),
        # RunConfig(Model="REL_EVAL"),
        # RunConfig(Model="IH",),
        RunConfig(Model="AF_EVAL", local_search=True),
        # RunConfig(Model="REL_EVAL", local_search=True),
        # RunConfig(Model="IH", local_search=True),
    ]

    for run in run_configs:
        current_size = copy.deepcopy(size)
        cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
        instances(cfg)
# ==============================================================================


# ==============================================================================
# BARRIDO PARAMÉTRICO (SENSITIVITY ANALYSIS SWEEP)
# ==============================================================================
run_configs = [
    RunConfig(Model="MS_linear", W_cts=True),
    RunConfig(Model="AF_EVAL"),
    RunConfig(Model="REL_EVAL"),
    RunConfig(Model="IH"),
]
# ==============================================================================
# COMPONENTS SWEEP
# ==============================================================================
comps = [4,5,6,7,8,9,10]
if comp_sweep:
    for val in comps: 

        comp = val

        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="comp", param_name="comp", param_value=val)

    comp = 5 # reset base value

# ==============================================================================
# PRODUCTS SWEEP
# ==============================================================================
prod = [3,4,5,6,7,8,9]
if prod_sweep:
    for val in prod:    

        prod = val

        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="prod", param_name="prod", param_value=val)

    prod = 4 # reset base value

# ==============================================================================
# BRANCHING SWEEP
branching = [
            [5,5,5,2,1,1,1],
            [10,5,2,2,1,1,1],
            [20,5,2,1,1,1,1],
            [50,2,2,1,1,1,1],
            [125,2,1,1,1,1,1],
            ]
# ==============================================================================
if branching_sweep:
    i=0
    for val in branching:    

        branching = val
        scenarios = math.prod(branching)   # 128 scenarios
        i+=1
        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="branching", param_name="branching", param_value=i)

    branching = [2,2,2,2,2,2,2] # reset base value
    scenarios = math.prod(branching)   # 128 scenarios

# ==============================================================================
# LEAD TIMES SWEEP
# ==============================================================================
run_configs = [
    RunConfig(Model="MS_linear", W_cts=True),
    RunConfig(Model="REL_EVAL"),
    RunConfig(Model="AF_EVAL", phi_mode="eps"),
    RunConfig(Model="AF_EVAL", phi_mode="eps_delta"),
    RunConfig(Model="AF_EVAL", phi_mode="eps_lt"),
    RunConfig(Model="AF_EVAL", phi_mode="eps_delta_lt"),
]

lead_times = [2,3,4,5]
if lead_time_sweep:
    for val in lead_times:    

        ub_L = val

        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="lead_times", param_name="lead_times", param_value=val)

    ub_L = 2 # reset base value

# ==============================================================================
# DEMAND SHOCK SWEEP
# ==============================================================================
dem_var = [0.15,0.3,0.45,0.6]
if dem_sweep:
    for val in dem_var:    

        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, 1-val, 1+val, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="demand", param_name="demand", param_value=val)


# ==============================================================================
# Out of Sample SWEEP
branching = [
            [5,5,5,2,1,1,1],
            [10,5,2,2,1,1,1],
            [20,5,2,1,1,1,1],
            [50,2,2,1,1,1,1],
            [125,2,1,1,1,1,1],
            ]
# ==============================================================================
if oos_sweep:
    i=0
    for val in branching:    

        branching = val
        scenarios = math.prod(branching)   # 128 scenarios
        i+=1
        size = ProblemSize(inst, comp, prod, stages, scenarios, branching, seed, time_limit)
        bom = BomConfig(min_use, max_use, other)
        costs = CostConfig(min_cost, max_cost, inv_factor, I0)
        price = PriceConfig(lb_price, ub_price, step_price)
        demand = DemandConfig(a, b, lb_epsilon, ub_epsilon, mu_delta, std_delta)
        lead_times = LeadTimeConfig(lb_L, ub_L, det)
        Output = OutputConfig(show_var, lambda_app, show_heatmap, show_boxplot, show_candlestick, show_kpis, 
                            vss_calc, evpi_calc, vss_ts_calc)

        for run in run_configs:
            current_size = copy.deepcopy(size)
            cfg = ExperimentConfig(current_size, bom, costs, price, demand, lead_times, run, Output, iter)
            
            _,_ = instances(cfg, tag="branching", param_name="branching", param_value=i)

    branching = [2,2,2,2,2,2,2] # reset base value
    scenarios = math.prod(branching)   # 128 scenarios